from .flux_lora_loader import (
    NODE_CLASS_MAPPINGS as LORA_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as LORA_NODE_DISPLAY_NAME_MAPPINGS,
)
from .flux_conditioning_controls import (
    NODE_CLASS_MAPPINGS as CONDITIONING_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as CONDITIONING_NODE_DISPLAY_NAME_MAPPINGS,
)
from .flux_image_postprocess import (
    NODE_CLASS_MAPPINGS as IMAGE_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as IMAGE_NODE_DISPLAY_NAME_MAPPINGS,
)
from .flux_preflight_advisor import (
    NODE_CLASS_MAPPINGS as PREFLIGHT_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as PREFLIGHT_NODE_DISPLAY_NAME_MAPPINGS,
)

WEB_DIRECTORY = "./js"

NODE_CLASS_MAPPINGS = {
    **LORA_NODE_CLASS_MAPPINGS,
    **CONDITIONING_NODE_CLASS_MAPPINGS,
    **IMAGE_NODE_CLASS_MAPPINGS,
    **PREFLIGHT_NODE_CLASS_MAPPINGS,
}

NODE_DISPLAY_NAME_MAPPINGS = {
    **LORA_NODE_DISPLAY_NAME_MAPPINGS,
    **CONDITIONING_NODE_DISPLAY_NAME_MAPPINGS,
    **IMAGE_NODE_DISPLAY_NAME_MAPPINGS,
    **PREFLIGHT_NODE_DISPLAY_NAME_MAPPINGS,
}

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS", "WEB_DIRECTORY"]
